# docker-compose.yml
# ----------------------------------------------------------------------------
# Composes Docker containers and volumes to a runnable Java EE application
# ----------------------------------------------------------------------------
#
---
services:

  downstream-a:
    image: docker.cloudtrain.aws.msgoat.eu/cloudtrain/cnj-resilience-downstream-a:latest
    ports:
      - "31080:8080"
    environment:
      DOCKER_JAVA_OPTS: "-Xms1g -Xmx1g"

  downstream-b:
    image: docker.cloudtrain.aws.msgoat.eu/cloudtrain/cnj-resilience-downstream-b:latest
    ports:
      - "32080:8080"
    environment:
      DOCKER_JAVA_OPTS: "-Xms1g -Xmx1g"

  backend:
    image: docker.cloudtrain.aws.msgoat.eu/cloudtrain/cnj-resilience-backend-micro:latest
    ports:
      - "38080:8080"
    environment:
      DOCKER_JAVA_OPTS: "-Xms1g -Xmx1g"
      PAYARA_LOGGING_FORMAT: "TEXT"
      CLOUDTRAIN_SERVICES_RECOMMENDATIONS_MP_REST_URL: "http://downstream-a:8080"
      CLOUDTRAIN_SERVICES_WATCHLIST_MP_REST_URL: "http://downstream-b:8080"
      CNJ_OBSERVABILITY_REST_TRACING_ENABLED: "true"
    depends_on:
      downstream-a:
        condition: service_started
      downstream-b:
        condition: service_started

